filename: 10k-mono.mono1d.yaml
nproc: 4
store_temp: false
parameters:
    - name: axial
      length: 1
      path: input.model.unit_002.col_dispersion
      min_value: 1.0e-9
      max_value: 1.0e-4
objectives: 
    - name: outlet
      filename: chromatogram-corrected.csv
      # times: timesteps.txt
      score: sse
      path: output.solution.unit_003.solution_outlet_comp_000
      match_solution_times: true
algorithm: 
    name: nsga3
    pop_size: 10
termination:
  # x_tol: 1e-8
  # cv_tol: 1e-6
  f_tol: 1e-9
  nth_gen: 2
  n_last: 10
  n_max_gen: 10
  n_max_evals: 100000
