filename: 10k-mono.mono1d.yaml
nproc: 4
store_temp: false
transforms:
  parameters: lognorm
parameters:
    - name: axial
      length: 1
      path: input.model.unit_002.col_dispersion
      min_value: 1.0e-9
      max_value: 1.0e-4
    - name: flowrate
      type: element
      length: 1
      path: input.model.connections.switch_000.connections
      index: [6]
      min_value: 1.e-10
      max_value: 1e-9
      copy_to_path: input.model.connections.switch_000.connections
      copy_to_index: [[13, 20]]
objectives: 
    - name: outlet
      filename: chromatogram-corrected.csv
      score: sse
      path: output.solution.unit_003.solution_outlet_comp_000
algorithm: 
  name: unsga3
  pop_size: 20
  # init_sobol: true
termination:
  # x_tol: 1e-8
  # cv_tol: 1e-6
  f_tol: 1e-12
  nth_gen: 2
  n_last: 5
  n_max_gen: 100
  n_max_evals: 100000
